window.decorations = "None"
window.startup_mode = "Fullscreen"

mouse.hide_when_typing = true

font.normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
font.size = 16

import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]
