window.decorations = "Full"
window.startup_mode = "Windowed"
window.option_as_alt = "OnlyLeft"
window.padding = { x = 5, y = 3 }

shell.program = "/opt/homebrew/bin/tmux"

mouse.hide_when_typing = true

font.normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
font.size = 16

import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]
